spring:
    application:
        name: iflow

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
        username: ${MYSQL_USER}
        password: '${MYSQL_PASSWORD}'

    jpa:
        open-in-view: false
        show-sql: false
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect
